name: 'CloudFormation Update'
description: 'Update a stack specifying only changing parameters and verify the result.'
author: Juan Andres Zeni (juanandreszeni@gmail.com)
branding:
  icon: 'refresh-cw'
  color: 'purple'
runs:
  using: 'docker'
  image: 'Dockerfile'
